
language: java

jdk:
  - openjdk21

before_install:
  - chmod +x mvnw

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean install

notifications:
  email: diricannuman@gmail.com 



